version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./logs:/app/backend/logs
    networks:
      - app-network
    env_file:
      - ./backend/.env
networks:
  app-network:
    driver: bridge